name: Build and Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  packages: read

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
    NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v1
        id: pages
      # - name: Install Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      - uses: pnpm/action-setup@v2
        with:
            version: 8
      - run: pnpm install --frozen-lockfile
      # - run: npm install
      - run: pnpm build
        env:
          VITE_GOOGLE_OAUTH2_CREDENTIALS: ${{ secrets.VITE_GOOGLE_OAUTH2_CREDENTIALS }}
          VITE_AUTH_CALLBACK_URL_BASE: 'https://peralmq.github.io/vwmp/'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment